In [23]:
import numpy as np

### Numpy ndarray:多维数组对象  
ndarray是python中一个快速的灵活的大型数据集容器

#### 生成 ndarray

In [2]:
data=np.random.randn(2,3)
data

array([[ 1.61761354,  0.0268366 ,  0.59276651],
       [ 0.02889422, -0.8500577 , -0.35742875]])

In [3]:
# 一个ndarry是一个通用的多维同类数据容器  
# 每个数组都有一个shape属性,用来表征数组每一维度的数量
# 每个数组都有一个dtype属性,用来描述数组的数据类型
display(data.shape)
display(data.dtype)

(2, 3)

dtype('float64')

In [4]:
# array 将输入数据转换为ndarray,默认复制所有的输入数据
# asarray 如果输入已经是ndarray则不再复制
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
display(arr2.ndim)
display(arr2.shape)

2

(2, 4)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.empty((2,3,4))

array([[[4.545e-321, 4.545e-321, 3.320e-321, 3.320e-321],
        [2.490e-321, 2.490e-321, 3.360e-321, 3.360e-321],
        [4.150e-321, 4.150e-321, 4.585e-321, 4.585e-321]],

       [[5.692e-321, 5.692e-321, 5.731e-321, 5.731e-321],
        [5.751e-321, 5.751e-321, 5.632e-321, 5.632e-321],
        [5.771e-321, 5.771e-321, 5.790e-321, 5.790e-321]]])

In [9]:
rang=np.arange(15)
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.ones_like(rang)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.full((2,2),9.0)

array([[9., 9.],
       [9., 9.]])

In [14]:
np.full((4,),9)

array([9, 9, 9, 9])

In [15]:
display(np.eye(2))
display(np.identity(2))

array([[1., 0.],
       [0., 1.]])

array([[1., 0.],
       [0., 1.]])

#### ndarray的数据类型  
92页

In [16]:
# astype显式地转换数组的数据类型
arr=np.array([1,2,3,4])
arr2=arr.astype(np.float32)#复制操作
display(arr.dtype)
display(arr2.dtype)

dtype('int32')

dtype('float32')

In [22]:
# 把浮点数转换成整数,小数点后的部分被抹除
arr3=np.array([1.22,2.83,3.11])
arr4=arr3.astype(np.int32)
display(arr3)
display(arr4)

array([1.22, 2.83, 3.11])

array([1, 2, 3])

In [18]:
num_str=np.array(['1.2','2','3.1111'])
num_str.astype(float)

array([1.2   , 2.    , 3.1111])

#### 数组运算

In [32]:
# 向量化:进行批量操作而无需迭代
# 两个等尺寸数组之间的算术操作都应用了逐元素操作的方式
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
display(arr)
display(arr*arr)
display(arr-arr)
display(1/arr)
display(arr**0.5)

array([[1., 2., 3.],
       [4., 5., 6.]])

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
# 布尔数组
arr2=np.array([[0,4,1],[7,2,12]],dtype=np.float64)
display(arr2)
display(arr2>arr)

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

array([[False,  True, False],
       [ True, False,  True]])

#### 索引与切片

In [38]:
# 选中数据的子集或某个单元的元素
arr=np.arange(10)
display(arr[5:8])
arr[5:8]=1
display(arr)

array([5, 6, 7])

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

In [41]:
#数组的切片是原数组的视图,也就是说数据并不是被复制了,任何对视图的修改都会反映到原数组上
arr_slice=arr[5:8]
display(arr_slice)
arr_slice[1]=1024
display(arr)
arr_slice[:]=512#引用数组的所有值
display(arr)

array([512, 512, 512])

array([   0,    1,    2,    3,    4,  512, 1024,  512,    8,    9])

array([  0,   1,   2,   3,   4, 512, 512, 512,   8,   9])

In [45]:
arr_copy=arr[5:8].copy()# 数组切片的拷贝,而不是视图
display(arr_copy)
arr_copy[:]=200
display(arr_copy)
display(arr)

array([512, 512, 512])

array([200, 200, 200])

array([  0,   1,   2,   3,   4, 512, 512, 512,   8,   9])

In [49]:
# 在二维数组中,每个索引值对应的元素不再是一个值,而是一个一维数组
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
display(arr2d)
arr2d[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

In [51]:
#以下两种方式效果一样
# 二维数组上的索引,可以把0轴看作是x 行,把1轴看作是y 列
display(arr2d[0][0])
display(arr2d[0,0])

1

1

In [55]:
# 多维数组中,返回的对象将是降低一个维度的数组
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
display(arr3d)
display(arr3d[1])
arr3d[1].ndim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[ 7,  8,  9],
       [10, 11, 12]])

2

In [56]:
arr3d[1]=0
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [59]:
display(arr3d[0,1])
display(arr3d[0][1])
#返回的都是数组视图

array([4, 5, 6])

array([4, 5, 6])

In [61]:
arr[1:3]

array([1, 2])

In [63]:
arr2d[:2]#数组延着0轴进行切片

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr2d[:2,1:]#数组先切0轴之后再切1轴

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[:2,2]#索引和切片混用可以得到低维度的切片

array([3, 6])

In [68]:
arr2d[:,:1]#单独一个冒号表示选择整个轴上的数组

array([[1],
       [4],
       [7]])

In [72]:
arr2d[:,:1]=0
arr2d#视图

array([[0, 2, 3],
       [0, 5, 6],
       [0, 8, 9]])

#### 布尔索引