In [1]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
import numpy as np

### 常量求导（g.gradient只能调用一次）

In [26]:
x = tf.constant(3.0)
with tf.GradientTape() as g:# 作用域
    g.watch(x)#watch 观察，查看
    y = x**2
    t = g.gradient(y,x) # 调用gradient()作用域结束了
t2 =  g.gradient(y,x)# 第二次调用
print(t2)
display(t)

RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

### GradientTape多次连续求导

In [23]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as g:
    g.watch(x)# watch定义求导的变量，默认情况下，Tape观察变量
    y = x**2
    z = y**2
t1 = g.gradient(y,x)# x**2 -------->2x
t2 = g.gradient(z,x)# x**4 -------->4x**3
display(t1,t2)
# del 内存中的对象删除
del g

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

### GradientTape自动对变量求导

In [18]:
x = tf.Variable(3.0)# 变量，可变量，方程的一个元
f = lambda x:x**3 + 2*x + 5 # f(x) = wx + b
with tf.GradientTape() as g:#变量不需要watch，自动监控
    y = f(x)
g.gradient(y,x)# 3*x**2 + 2 = 3*3**2 + 2 = 29

<tf.Tensor: shape=(), dtype=float32, numpy=29.0>

### GradientTape给了两个变量

In [29]:
x = tf.Variable([1.0,3.0])
y = tf.Variable([2.0,7.0])
f = lambda x,y:x**2 + y**3 + 3
with tf.GradientTape() as g:
    z = f(x,y)
    gradients = g.gradient(z,[x,y])
gradients

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 6.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 12., 147.], dtype=float32)>]

$$f(x,y) = x^2 + y^3 + 3$$

$$f'(x) = 2x$$

$$f'(y) = 3y^2$$