In [1]:
import numpy as np

import tensorflow as tf

In [2]:
image = np.random.randint(0,3,size = (5,5))
image

array([[2, 2, 2, 1, 2],
       [0, 2, 1, 1, 2],
       [0, 1, 1, 1, 0],
       [0, 2, 1, 2, 0],
       [1, 1, 1, 2, 0]])

In [4]:
# 卷积运算左上角的数值1，右下角数值0
filter_ = np.random.randint(-1,2,size = (3,3))
filter_

array([[-1,  0,  1],
       [ 1,  1,  0],
       [ 0, -1,  0]])

In [9]:
# Given an input tensor of shape `[batch, in_height, in_width, in_channels]`
# input 必须是4维
# batch：样本数量
# in_height:高度
# in_width:宽度
# in_channels:颜色通道（红绿蓝），通过数量是1个：黑白图片
# numpy 里面是有reshape的，条件限制：reshape之前和之后，数据量不变
input_layer = tf.reshape(image,shape = [1,5,5,1])
input_layer = tf.cast(input_layer,dtype=tf.float32)

# 参数二filters 卷积核，复数，多个卷积核
# a filter / kernel tensor of shape
# `[filter_height, filter_width, in_channels, out_channels]`, this op
# filter_height 卷积核高度
# filter_width  卷积核宽度
# in_channels    输入数据的颜色通道，应该和输入数据的in_channels 保持一直
# out_channels   输出卷积核数量，人为定义的
filters = tf.reshape(filter_,shape = [3,3,1,1])
kernel = tf.cast(filters,dtype= tf.float32)

# 参数三，strides步幅，扫描
# strides: An int or list of `ints` that has length `1`, `2` or `4`.  The
#     stride of the sliding window（扫描窗口） for each dimension of `input`.

# 参数四：padding: Either the `string` `"SAME"` or `"VALID"`
# 现在，使用别人写好的代码，那么必须遵循人家规定条件
# google开发人员，规定输入数据必须是4维。
conv = tf.nn.conv2d(input = input_layer,
                    filters = kernel,
                    strides =[1,1,1,1] ,
                    padding='SAME',#原数据进行填充
                    data_format='NHWC')#NHWC ---->N代表样本数量，H代表height，W代表width，C代表channel
# 输入的数据是四维的，输出的数据也是4维的
conv.numpy().reshape(5,5)

array([[2., 2., 3., 2., 1.],
       [2., 1., 1., 1., 2.],
       [2., 0., 0., 1., 0.],
       [0., 2., 2., 0., 1.],
       [3., 3., 2., 2., 0.]], dtype=float32)