In [1]:
# import
import numpy as np

In [2]:
# init
x=np.arange(10)
y=np.array([1,1,1,-1,-1,-1,1,1,1,-1])
w1=np.array([0.1]*10)

In [3]:
for v in np.arange(1.5,10,1):
    G1=[1 if i<v else -1 for i in x]
    err=(G1!=y)*w1
    err=err.sum()
    print(v,round(err,4),end='   ')
    G1=[-1 if i<v else 1 for i in x]
    err=((G1!=y)*w1).sum()
    print(round(err,4))

1.5 0.4   0.6
2.5 0.3   0.7
3.5 0.4   0.6
4.5 0.5   0.5
5.5 0.6   0.4
6.5 0.5   0.5
7.5 0.4   0.6
8.5 0.3   0.7
9.5 0.4   0.6


In [4]:
v=2.5
G1=np.array([1 if i<v else -1 for i in x])
err1=round(((G1!=y)*w1).sum(),4)
alpha1=round(np.log((1-err1)/err1)/2,4)
alpha1

0.4236

In [5]:
f1=np.sign(alpha1*G1)
(f1==y).all()

False

In [6]:
w2=(w1*np.exp(-alpha1*y*G1))/(w1*np.exp(-alpha1*y*G1)).sum()

In [7]:
for v in np.arange(1.5,10,1):
    G2=[1 if i<v else -1 for i in x]
    err2=(G2!=y)*w2
    err2=err2.sum()
    print(v,round(err2,4),end='   ')
    G2=[-1 if i<v else 1 for i in x]
    err2=((G2!=y)*w2).sum()
    print(round(err2,4))

1.5 0.5714   0.4286
2.5 0.5   0.5
3.5 0.5714   0.4286
4.5 0.6428   0.3572
5.5 0.7143   0.2857
6.5 0.5476   0.4524
7.5 0.381   0.619
8.5 0.2143   0.7857
9.5 0.2857   0.7143


In [8]:
v2=8.5
G2=np.array([1 if i<v2 else -1 for i in x])
err2=round(((G2!=y)*w2).sum(),4)
alpha2=round(np.log((1-err2)/err2)/2,4)
alpha2

0.6496

In [9]:
f2=np.sign(alpha1*G1+alpha2*G2)
print((f2==y).all())
print(f2)
print(y)

False
[ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [10]:
w3=(w2*np.exp(-alpha2*y*G2))/(w2*np.exp(-alpha2*y*G2)).sum()
w3

array([0.04545785, 0.04545785, 0.04545785, 0.16666494, 0.16666494,
       0.16666494, 0.10605793, 0.10605793, 0.10605793, 0.04545785])

In [11]:
for v in np.arange(1.5,10,1):
    G3=[1 if i<v else -1 for i in x]
    err3=(G3!=y)*w3
    err3=err3.sum()
    print(v,round(err3,4),end='   ')
    G3=[-1 if i<v else 1 for i in x]
    err3=((G3!=y)*w3).sum()
    print(round(err3,4))

1.5 0.3636   0.6364
2.5 0.3182   0.6818
3.5 0.4848   0.5152
4.5 0.6515   0.3485
5.5 0.8182   0.1818
6.5 0.7121   0.2879
7.5 0.6061   0.3939
8.5 0.5   0.5
9.5 0.5455   0.4545


In [12]:
v3=5.5
G3=np.array([-1 if i<v3 else 1 for i in x])
err3=round(((G3!=y)*w3).sum(),4)
alpha3=round(np.log((1-err3)/err3)/2,4)
alpha3

0.7521

In [13]:
w4=(w3*np.exp(-alpha3*y*G3))/(w3*np.exp(-alpha3*y*G3)).sum()
w4

array([0.12501321, 0.12501321, 0.12501321, 0.10184168, 0.10184168,
       0.10184168, 0.06480738, 0.06480738, 0.06480738, 0.12501321])

In [16]:
f3=np.sign(alpha1*G1+alpha2*G2+alpha3*G3)
(f3==y).all()

True