In [1]:
import torch

In [2]:
batch_size=1
seq_len=3
input_size=4
hidden_size=2

In [3]:
cell=torch.nn.RNNCell(input_size=input_size,
                      hidden_size=hidden_size)

In [4]:
data=torch.randn(seq_len,batch_size,input_size)
hidden=torch.zeros(batch_size,hidden_size)

In [5]:
display(data)
display(hidden)

tensor([[[-1.6470, -0.8275, -0.3770,  0.0177]],

        [[ 0.6591, -1.2432,  0.6157,  0.3194]],

        [[-0.5039,  0.6118,  1.1902,  1.0239]]])

tensor([[0., 0.]])

In [6]:
for i,xy in enumerate(data):
    print('Input size: ',data.shape)
    hidden=cell(xy,hidden)
    print('Output size: ',hidden.shape)
    print(hidden.data)

Input size:  torch.Size([3, 1, 4])
Output size:  torch.Size([1, 2])
tensor([[-0.8177,  0.3621]])
Input size:  torch.Size([3, 1, 4])
Output size:  torch.Size([1, 2])
tensor([[-0.9220, -0.9612]])
Input size:  torch.Size([3, 1, 4])
Output size:  torch.Size([1, 2])
tensor([[ 0.1363, -0.6614]])


In [7]:
import numpy as np

In [8]:
batch_size=1
input_size=4
hidden_size=4

In [9]:
idx2char=['e','h','l','o']
x_data=[1,0,2,2,3]
y_data=[3,1,2,3,2]
one_hot_lookup=np.identity(4)
x_one_hot=[one_hot_lookup[x] for x in x_data]
inputs=torch.Tensor(x_one_hot).view(-1,batch_size,input_size)
labels=torch.LongTensor(y_data).view(-1,1)

In [10]:
labels

tensor([[3],
        [1],
        [2],
        [3],
        [2]])

In [11]:
class Model(torch.nn.Module):
    def __init__(self,batch_size,input_size,hidden_size):
        super(Model,self).__init__()
        self.batch_size=batch_size
        self.input_size=input_size
        self.hidden_size=hidden_size
        self.cell=torch.nn.RNNCell(input_size=self.input_size,hidden_size=self.hidden_size)
    def forward(self,inputs,hidden):
        hidden=self.cell(inputs,hidden)
        return hidden
    def init_hidden(self):
        return torch.zeros(self.batch_size,self.hidden_size)
model=Model(batch_size=batch_size,input_size=input_size,hidden_size=hidden_size)

In [12]:
criterion=torch.nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(params=model.parameters(),lr=0.1)

In [16]:
for epoch in range(10):
    loss=0
    optimizer.zero_grad()
    hidden=model.init_hidden()
    for inputs_,labels_ in zip(inputs,labels):
        hidden=model(inputs_,hidden)
#         print(hidden)
        loss+=criterion(hidden,labels_)
#         print(labels_)
        _,idx=hidden.max(dim=1)
        print(idx2char[idx.item()],end='')
    loss.backward()
    optimizer.step()
    print(', Epoch [%d/15] loss=%.4f' % (epoch+1, loss.item()))

ohlll, Epoch [1/15] loss=2.3090
ohlll, Epoch [2/15] loss=2.2944
ohlll, Epoch [3/15] loss=2.2816
ohlll, Epoch [4/15] loss=2.2708
ohlll, Epoch [5/15] loss=2.2616
ohlll, Epoch [6/15] loss=2.2537
ohlll, Epoch [7/15] loss=2.2471
ohlll, Epoch [8/15] loss=2.2413
ohlll, Epoch [9/15] loss=2.2362
ohlll, Epoch [10/15] loss=2.2318
