In [1]:
import torch

### Tensor&tensor几点区别
torch.Tensor : torch.empty&torch.tensor之间的一种混合,使用全局默认的dtype(FloatTensor)  
torch.Tensor(1) : 返回大小为1的张量,其值为随机初始化的值  
torch.tensor : 从数据中推断数据类型  
torch.tensor(1) : 返回标量,其值为1

In [71]:
t1=torch.Tensor(1)
t2=torch.tensor(1)
print('Tensor--> {}, 类型: {}'.format(t1,t1.type()))
print('tensor--> {}, 类型: {}'.format(t2,t2.type()))

Tensor--> tensor([0.]), 类型: torch.FloatTensor
tensor--> 1, 类型: torch.LongTensor


### 创建Tensor

In [72]:
import numpy as np

In [83]:
t3=np.ndarray([1,2,3])
torch.Tensor(t3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [106]:
torch.from_numpy(t3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [86]:
list_a=[1,2,3,4]
torch.Tensor(list_a)

tensor([1., 2., 3., 4.])

In [93]:
torch.eye(3) # torch.eye(3,3) eye(rows,columns)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [95]:
torch.logspace(2,3,10) #从10^start 到10^end 均匀分成steps份

tensor([ 100.0000,  129.1550,  166.8101,  215.4435,  278.2560,  359.3814,
         464.1589,  599.4843,  774.2637, 1000.0000])

In [102]:
# ones()
# zeros()
# linspace()
# rand/randn [0,1)均匀分布/标准正态分布

### 修改Tensor形状
