# 数字,日期,时间

### 对数值进行取整  
round(value, ndigits)

In [1]:
round(1.23456789, 4)

1.2346

In [2]:
round(123456789, -1) # ndigits可以为负数 相应的取整 十位 百位 千位...

123456790

### 执行精确的小数计算  
decimal.Decimal()

In [3]:
a = 4.2
b = 2.1
a + b

6.300000000000001

In [4]:
from decimal import Decimal # Decimal对象能以任何期望的方式来工作 支持所有常见的素雪操作
a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [5]:
# decimal模块主要功能是允许控制计算过程的各个方面
# decimal模块实现了IBM的通用十进制算数规范
# General Decimal Arithmetic Specification
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
a / b

Decimal('0.7647058823529411764705882353')

In [6]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.765


In [7]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a/ b)

0.76470588235294117647058823529411764705882352941176


In [8]:
# float 提供17位的精度
nums = [1.23e+18 , 1, -1.23e+18]
sum(nums)

0.0

In [9]:
# 更加精确的实现
import math
math.fsum(nums)

1.0

### 对数值做格式化输出

In [10]:
# 对单独的数值做格式化输出 使用内建的format()函数即可
x = 1234.56789
format(x, '0.2f')

'1234.57'

In [11]:
format(x, '^10.3f')

' 1234.568 '

In [12]:
format(x, '>20.1f')

'              1234.6'

In [13]:
# 采用科学计数法 e或E
format(x, 'e')

'1.234568e+03'

In [14]:
format(x, '0.2E')

'1.23E+03'

In [15]:
# 指定宽度与精度
# '[<>^]?width[,]?(.digits)?'
'{:0,.2f}'.format(x)

'1,234.57'

In [16]:
# 利用str.translate()交换不同字符
asia = 'Asia'
swap_separator = {ord('A'): 'a', ord('a'): 'A'}
asia.translate(swap_separator)

'asiA'

### 同二进制,八进制,十六进制打交道

In [17]:
a = 1234

In [18]:
bin(a) # 二进制

'0b10011010010'

In [19]:
oct(a) # 八进制

'0o2322'

In [20]:
hex(a) # 十六进制

'0x4d2'

In [21]:
format(a, 'o')  # 'b o x'

'2322'

In [22]:
b = -1234

In [23]:
format(2**32 + b, 'b')

'11111111111111111111101100101110'

In [24]:
int('11111111111111111111101100101110', 2)

4294966062

### 字节串的打包与解包

In [25]:
a = 89562233022300055123665959565

In [26]:
data = a.to_bytes(16, 'big')
data

b'\x00\x00\x00\x01!d$\x8c\xc5\x83U\xeb\xaf]:\x8d'

In [27]:
data2 = a.to_bytes(16, 'little')
data2

b'\x8d:]\xaf\xebU\x83\xc5\x8c$d!\x01\x00\x00\x00'

In [28]:
display(len(data))
display(len(data2))

16

16

In [29]:
int.from_bytes(data, 'big')

89562233022300055123665959565

In [30]:
int.from_bytes(data2, 'little')

89562233022300055123665959565

In [31]:
import struct
hi, low = struct.unpack('>QQ', data)

In [32]:
(hi << 64) + low

89562233022300055123665959565

In [33]:
x = 520 ** 23
x

293816988845484760324348363160379247820800000000000000000000000

In [34]:
x.to_bytes(16, 'big') # 16位存不下

OverflowError: int too big to convert

In [ ]:
int.bit_length(x)

In [ ]:
nbytes, rem = divmod(x.bit_length(), 8)

In [ ]:
for i in range(rem):
    nbytes += 1

In [ ]:
x.to_bytes(nbytes, 'big')

### 复数运算

In [ ]:
a = complex(2, 4)
a

In [ ]:
b = 3 - 5j
b

In [ ]:
print(a.real) # 实部
print(a.imag) # 虚部
a.conjugate() # 共轭值

In [ ]:
print('a', a)
print('b', b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
abs(a)

In [ ]:
# 复数的函数操作
import cmath
print(cmath.sin(a)) # 正弦
print(cmath.cos(a)) # 余弦
print(cmath.exp(a)) # 平方根
cmath.tan(a)

In [ ]:
import numpy as np
np.sin(a)

### 无穷大和NAN

In [35]:
a = float('inf')
a

inf

In [36]:
b = float('-inf')
b

-inf

In [37]:
c = float('nan')
d = float('nan')
c

nan

In [38]:
c is d # 两个 NAN 不相等 not a number 

False

In [39]:
import math
print(math.isinf(a))
print(math.isnan(c))

True
True


### 分数计算

In [2]:
from fractions import Fraction
a = Fraction(4, 5)
b = Fraction(12, 20)
c = a * b

Fraction(7, 5)

In [4]:
print(a + b)
print(a * b)

7/5
12/25


In [42]:
c.numerator # 分子

12

In [43]:
c.denominator # 分母

25

In [44]:
float(c)

0.48

In [45]:
12/25


0.48

In [46]:
c.limit_denominator(50)

Fraction(12, 25)

In [47]:
# 浮点数 转化为 分数 
k = 2.25
w = Fraction(*k.as_integer_ratio())
w

Fraction(9, 4)

### Numpy 

In [48]:
import numpy as np
A = np.arange(1, 10).reshape(-1, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.where(A < 5, 0, A)

array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])

### 矩阵和线性代数运算

In [50]:
B = np.matrix(A)
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
A.dot(B)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [52]:
B.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [53]:
V = np.matrix([[2], [6], [4]])
V

matrix([[2],
        [6],
        [4]])

In [54]:
V.I

matrix([[0.03571429, 0.10714286, 0.07142857]])

In [55]:
m = B * V
m

matrix([[26],
        [62],
        [98]])

In [56]:
np.linalg.det(A) # determinant 决定因素 行列式

0.0

In [58]:
np.linalg.solve() # Ax = B 矩阵A B 求x

TypeError: _solve_dispatcher() missing 2 required positional arguments: 'a' and 'b'

### 随机选择

In [ ]:
import random

In [ ]:
a_list = [1, 2, 3, 4, 5, 6]

In [ ]:
random.choice(a_list) # 随机选择一个数

In [ ]:
random.sample(a_list, 3) # 随机选择多个数

In [ ]:
random.shuffle(a_list) # 打乱顺序
a_list

In [ ]:
random.randint(0, 10) # 产生 [0-10] 随机整数

In [ ]:
random.random() # 产生 0-1之间的随机浮点数

In [ ]:
random.getrandbits(200) # 随机N位的比特位表示的整数

In [ ]:
random.seed() # 梅森旋转  种子

In [ ]:
random.uniform(1, 2) # 均匀分布

In [ ]:
random.gauss(1, 1) # 正态分布 standard deviation 标准偏差

### 时间换算

In [ ]:
from datetime import datetime, timedelta
from pytz import timezone
import pytz

In [ ]:
d = datetime.now()
d

In [ ]:
shanghai = timezone('Asia/ShangHai')
loc_d = shanghai.localize(d)
loc_d

In [ ]:
loc_d.astimezone(timezone('US/Central'))

In [ ]:
loc_d.astimezone(pytz.utc)

In [ ]:
pytz.common_timezones