In [1]:
# import
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

欧氏距离  
$L_2(x_i,x_j)=(\sum\limits_{l=1}^n|x_i^{(l)}-x_j^{(l)}|^2)^{\frac{1}{2}}$  
$L_2(x_i,x_j)=\sqrt{\sum\limits_{l=1}^n(x_i^{(l)}-x_j^{(l)})^2}$

In [10]:
# datas
X,y=datasets.load_iris(True)
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [13]:
# knn适合特征区分明显的
knn=KNeighborsClassifier(n_neighbors=5,p=2)
knn.fit(X_train,y_train)
y_=knn.predict(X_test)

In [14]:
# 准确率
print((y_test==y_).mean()) 
print(accuracy_score(y_test,y_)) 
print(knn.score(X_test,y_test)) 

0.9736842105263158
0.9736842105263158
0.9736842105263158


In [37]:
# knn概率划分
print(knn.predict_proba(X_test))

[[0.  0.  1. ]
 [0.  0.6 0.4]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.2 0.8]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]]
