In [1]:
# import
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn import datasets
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SelectFromModel

In [2]:
X,y=datasets.load_diabetes(True)
X.shape

(442, 10)

In [13]:
# 第一种写法预训练
ridge=Ridge().fit(X,y)
sfm=SelectFromModel(estimator=ridge,
                    threshold='median',
                    prefit=True)# prefit预训练
X2=sfm.transform(X)
X2.shape

(442, 5)

In [10]:
display(sfm.get_support())
np.abs(ridge.coef_).argsort()

array([False, False,  True,  True, False, False,  True,  True,  True,
       False])

array([4, 0, 5, 1, 9, 7, 6, 3, 8, 2], dtype=int64)

In [14]:
# 第二种写法没有预训练
ridge=Ridge()
sfm=SelectFromModel(estimator=ridge,
                    threshold='median',
                    prefit=False)# prefit预训练
X2=sfm.fit_transform(X,y)
X2.shape

(442, 5)

In [16]:
display(sfm.get_support())

array([False, False,  True,  True, False, False,  True,  True,  True,
       False])