In [1]:
# import
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn import datasets
from sklearn.linear_model import RidgeCV,LogisticRegression,LinearRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor
from xgboost import XGBClassifier,XGBRegressor
from sklearn.feature_selection import RFE,RFECV

![](./imgs/rfe.png)

In [6]:
X,y=datasets.load_boston(True)

In [5]:
rfe=RFE(estimator=AdaBoostRegressor(),
        n_features_to_select=8)
X2=rfe.fit_transform(X,y)
X2.shape

(178, 8)

In [8]:
rfe.get_support()

array([ True, False, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True])

![](./imgs/rfe2.png)

In [18]:
X,y=datasets.load_boston(True)
while True:
    s,f=X.shape
    l=[i for i in range(f)]
    if f==4:
        break
    linear=LinearRegression()
    linear.fit(X,y)
    index=np.argmin(linear.coef_)
    l.remove(index)
    X=X[:,l]
X[:5]

array([[ 18.   ,   0.   ,   6.575, 396.9  ],
       [  0.   ,   0.   ,   6.421, 396.9  ],
       [  0.   ,   0.   ,   7.185, 392.83 ],
       [  0.   ,   0.   ,   6.998, 394.63 ],
       [  0.   ,   0.   ,   7.147, 396.9  ]])

In [7]:
X,y=datasets.load_wine(True)
rfecv=RFECV(estimator=AdaBoostClassifier(),
            min_features_to_select=5,
            cv=5,# 交叉验证,5次循环 loop
            n_jobs=-1)
X2=rfecv.fit_transform(X,y)
X2.shape

(178, 7)

In [4]:
rfecv.get_support()

array([False, False, False, False, False,  True,  True, False,  True,
        True,  True,  True,  True])