In [9]:
# import
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [3]:
# datas
X,y=datasets.load_iris(True)

In [29]:
# pca  whiten标准化 n_components可以给数字也可以给百分比
pca=PCA(n_components=2,whiten=False)
# pca=PCA(n_components=0.98,whiten=False)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [35]:
# 降维
X_pca=pca.transform(X)
X_pca.shape
# X_pca=pca.fit_transform(X)

(150, 2)

In [31]:
# datas 元数据
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1024)

In [32]:
# 使用元数据
knn=KNeighborsClassifier(n_neighbors=5,weights='distance')
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

0.9666666666666667

In [33]:
# datas 降维数据
X_train2,X_test2,y_train2,y_test2=train_test_split(X_pca,y,test_size=0.2,random_state=1024)

In [34]:
# 使用降维数据
knn=KNeighborsClassifier(n_neighbors=5,weights='distance')
knn.fit(X_train2,y_train2)
knn.score(X_test2,y_test2)
y_=knn.predict(X_test2)
accuracy_score(y_test2,y_)

0.9666666666666667

手写PCA 

In [38]:
# 去中心化
A=X-X.mean(axis=0)

In [41]:
# 求协方差 两个属性进行对比
B=np.cov(A,rowvar=False)
B

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [42]:
# 方差
np.var(X[:,0])/149*150

0.6856935123042507

In [43]:
((X[:,0]-X[:,0].mean())**2).sum()/149

0.6856935123042507

In [46]:
# 特征值,特征向量计算
value,vector=np.linalg.eigh(B)
print(value,vector,sep='\n')

[0.02383509 0.0782095  0.24267075 4.22824171]
[[ 0.31548719  0.58202985  0.65658877 -0.36138659]
 [-0.3197231  -0.59791083  0.73016143  0.08452251]
 [-0.47983899 -0.07623608 -0.17337266 -0.85667061]
 [ 0.75365743 -0.54583143 -0.07548102 -0.3582892 ]]


In [49]:
# 根据特征值的权重,筛选特征向量
C=vector[:,2:]
C

array([[ 0.65658877, -0.36138659],
       [ 0.73016143,  0.08452251],
       [-0.17337266, -0.85667061],
       [-0.07548102, -0.3582892 ]])

In [57]:
# 进行矩阵运算
# A.dot(C)[:,[1,0]]
D=A.dot(C)
r,c=D.shape
coef=[-1 if (i+1)%2==0 else 1 for i in range(c)]
E=(D*coef)[:,[1,0]]
E

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

In [58]:
# whiten 标准化
F=(E-E.mean(axis=0))/E.std(axis=0)
F

array([[-1.30971087,  0.65054141],
       [-1.32435711, -0.36051227],
       [-1.40967409, -0.29522986],
       [-1.33958163, -0.64830449],
       [-1.33146886,  0.66552653],
       [-1.11293846,  1.50992585],
       [-1.37627274, -0.18221302],
       [-1.28141939,  0.33277896],
       [-1.4084016 , -1.17789289],
       [-1.30416299, -0.23173293],
       [-1.22325714,  1.3138624 ],
       [-1.2748859 ,  0.03000162],
       [-1.35947347, -0.47887104],
       [-1.57304515, -1.04159745],
       [-1.29049784,  2.40088235],
       [-1.16426043,  2.72533645],
       [-1.28014238,  1.65117453],
       [-1.29222826,  0.6351676 ],
       [-1.07339558,  1.7777797 ],
       [-1.26280003,  1.04600854],
       [-1.12728243,  0.79708495],
       [-1.24119316,  0.88191703],
       [-1.56920777,  0.27184488],
       [-1.12361159,  0.20104806],
       [-1.14948296, -0.07593489],
       [-1.2231214 , -0.29740403],
       [-1.20465318,  0.26671917],
       [-1.25027614,  0.74896183],
       [-1.28795287,

In [68]:
# n_components
v=value[::-1]
v

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [61]:
# 累加和
v.cumsum()/v.sum()

array([0.92461872, 0.97768521, 0.99478782, 1.        ])

In [67]:
pca=PCA(n_components=0.99)
pca.fit_transform(X).shape

(150, 3)