In [1]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer

In [2]:
one_hot=DictVectorizer()

In [11]:
X = [
    {'city': 'New York'},
    {'city': 'San Francisco'},
    {'city': 'Chapel Hill'}
]
one_hot.fit(X)

DictVectorizer()

In [12]:
one_hot.transform(X).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [13]:
one_hot.fit_transform(X).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
from sklearn.preprocessing import scale

In [19]:
X = np.array([
    [0., 0., 5., 13., 9., 1.],
    [0., 0., 13., 15., 10., 15.],
    [0., 3., 15., 2., 0., 11.]
])
stand=scale(X)
stand

array([[ 0.        , -0.70710678, -1.38873015,  0.52489066,  0.59299945,
        -1.35873244],
       [ 0.        , -0.70710678,  0.46291005,  0.87481777,  0.81537425,
         1.01904933],
       [ 0.        ,  1.41421356,  0.9258201 , -1.39970842, -1.4083737 ,
         0.33968311]])

In [33]:
np.var(stand,ddof=1)

0.8823529411764706

In [44]:
((stand.reshape(-1,1)-stand.reshape(-1,1).mean())**2).sum() / (stand.reshape(-1,1).shape[0]-1)

0.8823529411764706